### ISSUE TITLE
Supporting the simple(st) user story

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renga#117]
This is a meta-issue to keep track of work done to support the basic data science user story.

Please add a link to the relevant issue once it's created in the corresponding repository. Track the fine-grained issues in [sprint project](https://github.com/orgs/SwissDataScienceCenter/projects/15).

## 0. Housekeeping
- [x] Building docs from development on readthedocs
  - [x] renga-python
  - [x] renga
- [x] Updating all the READMEs on current masters to inform of work on development and make the instructions relevant to the development branch (see #116)
- [x] Integrate pieces of old Makefile that builds images across all repos with the new Makefile in development (#121)
- [ ] Travis-ci integration test for the development branch of `renga`
- make `make start` should bring up all the needed services
  - [x] ui (#125, related is https://github.com/SwissDataScienceCenter/renga-ui/pull/119))
  - [x] gitlab
  - [x] keycloak
  - [ ] storage (#128)

## 1. Initiate a project, import a dataset
- [ ] Finalize dataset import to work with renga repos (https://github.com/SwissDataScienceCenter/renga-python/issues/99)
- [x] update `.gitattributes` to track outputs of `renga run` and datasets in LFS (https://github.com/SwissDataScienceCenter/renga-python/issues/104)
* metadata 
  - [ ] document the ontology for projects, datasets, and CWL steps/workflows (https://github.com/SwissDataScienceCenter/renga-ontology/issues/3)
  - [x] include JSON-LD context with all metadata (https://github.com/SwissDataScienceCenter/renga-python/issues/105) (@jirikuncar)

## 2. Explore the dataset using a notebook (isolated environment)
- [ ] Look into capturing data artifacts the same way as with `renga run`

## 3. Run code on data, recording data provenance for reproducibility
- [ ] write user stories as test cases for `renga run`
- [x] Fix bugs with provenance calculation (https://github.com/SwissDataScienceCenter/renga-python/issues/106)
- [x] Resolve lineage in submodules (https://github.com/SwissDataScienceCenter/renga-python/issues/120)
- [x] Implement `renga status` that checks the validity of data provenance (https://github.com/SwissDataScienceCenter/renga-python/issues/107)
- [x] Write out workflows, fix problem with relative paths (https://github.com/SwissDataScienceCenter/renga-python/issues/98)
* (Dockerization & python environments -- for future sprint)

## 4. Push project to a server for sharing 
- [ ] Finalize storage service 
  * decouple from graph (https://github.com/SwissDataScienceCenter/renga-storage/issues/44)
  * update swagger and doc (https://github.com/SwissDataScienceCenter/renga-storage/issues/50)
  * define bucket/backend for LFS (https://github.com/SwissDataScienceCenter/renga-storage/issues/51)
- [ ] Memory provisioning for gitlab on testing.datascience.ch (@ebiiii / @leafty)
- [ ] Configure gitlab runners on k8s
  * Set up the ingress for notebook servers @leafty
  * Look into resource limitations of runners
- [ ] UI running on testing.datascience.ch
  * Resolve the token issue (reuse flask proxy from old UI? -> @3C111 / @leafty / @ebiiii) - authenticating the UI with keycloak done in https://github.com/SwissDataScienceCenter/renga-ui/pull/118
  * Configure deployment
- [ ] Manipulate project access settings 
- [ ] Initialize a project in UI (templates? Gitlab-ci, .renga metadata etc.)
- [ ] renga push/sync (index the provenance information)
- [ ] staging environment (https://github.com/SwissDataScienceCenter/incubator-renga-k8s/issues/1)

## 5. Validate results/workflows
- [ ] Troubleshoot the CI configuration -- related to https://github.com/SwissDataScienceCenter/renga-python/issues/102

## 6. Initiate discussions (ku) on the work done
- [x] create/participate in discussions (https://github.com/SwissDataScienceCenter/renga-ui/issues/108)
~~* Markdown editors~~
- [x] File browser for linking to entities in the repo
- [ ] Connect notebooks to live notebook server (https://github.com/SwissDataScienceCenter/renga-ui/issues/114)
~~* Dataset view, data preview~~

**Comment by rokroskar** [comment]
closing -- open items moved to #135
