### ISSUE TITLE
Supporting simple user story (2)

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renga#135]
This is a meta-issue to keep track of work done to support the **second** sprint of supporting the basic data science user story.

Please add a link to the relevant issue once it's created in the corresponding repository. Track the fine-grained issues in [sprint project](https://github.com/orgs/SwissDataScienceCenter/projects/16).

## 0. Housekeeping
- [x] documentation of development branches -- this includes making new examples using the new CLI, combing through the old docs to determine what should be discarded/updated (#140)
- [ ] Travis-ci integration test for the development branch of `renga` (https://github.com/SwissDataScienceCenter/renga/pull/139)
- [ ] add storage to docker-compose (#128)
- [x] plan UI work in next sprint (https://github.com/SwissDataScienceCenter/renga-ui/issues/132)
- [ ] design API to be used by UI client, CLI, and, perhaps, external users

## 1. Initiate a project, import a dataset
- [ ] Finalize dataset import to work with renga repos (https://github.com/SwissDataScienceCenter/renga-python/issues/99)
 - [ ] document the ontology for projects, datasets, and CWL steps/workflows 
   - [x] include `@context` and `@type` in docs https://github.com/SwissDataScienceCenter/renga-python/pull/143
   - [ ] https://github.com/SwissDataScienceCenter/renga-ontology/issues/3, see also [the data model described in the incubator UI](https://github.com/SwissDataScienceCenter/incubator-renga-ui/blob/master/doc/data_model.md)
- [x] Create a model object for project in JavaScript
- [ ] Support creating a project from the UI
 
## 2. Explore the dataset using a notebook (isolated environment)
~~Look into capturing data artifacts the same way as with `renga run`~~

## 3. Run code on data, recording data provenance for reproducibility
- [ ] POC for extending `renga run` to more flexible environments
  - [ ] a dockerized version of `renga run/rerun` 
  - [ ] using python environments in steps rerun on the server (à la [repo2docker](http://repo2docker.readthedocs.io/en/latest/usage.html))
- [ ] write user stories as test cases for `renga run`

## 4. Push project to a server for sharing 
- [ ] Finalize storage service 
  - [ ] decouple from graph (https://github.com/SwissDataScienceCenter/renga-storage/issues/44)
  - [ ] update swagger and doc (https://github.com/SwissDataScienceCenter/renga-storage/issues/50)
  - [ ] define bucket/backend for LFS (https://github.com/SwissDataScienceCenter/renga-storage/issues/51)
- [x] staging environment #130 
- [ ] Configure gitlab runners on k8s
~~allow runner to spawn daemonized containers~~
- [ ] POC for using jupyterhub with CI stages for deploying notebooks (@rokroskar)
- [x] deploy services using k8s chart on `testing.datascience.ch`
- [ ] Manipulate project access settings in the UI (https://github.com/SwissDataScienceCenter/renga-ui/issues/130)
- [ ] Initialize a project in UI (templates? Gitlab-ci, .renga metadata etc.; https://github.com/SwissDataScienceCenter/renga-ui/issues/129)
- [ ] renga push/sync (index the provenance information?)

## 5. Validate results/workflows
- [x] Troubleshoot the CI configuration -- related to https://github.com/SwissDataScienceCenter/renga-python/issues/102

## 6. Initiate discussions (ku) on the work done
~~Markdown editors~~
- [x] Connect notebooks to live notebook server (https://github.com/SwissDataScienceCenter/renga-ui/issues/114)
~~Dataset view, data preview~~

**Comment by rokroskar** [comment]
continues as https://github.com/SwissDataScienceCenter/renga/issues/146
