### ISSUE TITLE
Supporting simple user story (4)

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renga#159]
This is a meta-issue to keep track of work done to support the **fourth** sprint of supporting the basic data science user story.

Please add a link to the relevant issue once it's created in the corresponding repository. Track the fine-grained issues in [sprint project](https://github.com/orgs/SwissDataScienceCenter/projects/19).

## 0. Housekeeping
- [ ] document the ontology for projects, datasets, and CWL steps/workflows 
   - [ ] https://github.com/SwissDataScienceCenter/renga-ontology/issues/3, see also [the data model described in the incubator UI](https://github.com/SwissDataScienceCenter/incubator-renga-ui/blob/master/doc/data_model.md)
(https://github.com/SwissDataScienceCenter/renga/pull/139)
- [ ] add storage to docker-compose (#128)
- [ ] document how the storage service should be used with other components (@ebiiii)
- [ ] design API gateway / finalize proxy for UI (https://github.com/SwissDataScienceCenter/renga-ui/issues/127)  

## 1. Initiate a project, import a dataset
- [ ] Finalize dataset import to work with renga repos (https://github.com/SwissDataScienceCenter/renga-python/issues/99)
- [x] Support creating a project from the UI
 
## 3. Run code on data, recording data provenance for reproducibility
- [ ] POC for extending `renga run` to more flexible environments
  - [ ] a dockerized version of `renga run/rerun` 
  - [ ] using python environments in steps rerun on the server (à la [repo2docker](http://repo2docker.readthedocs.io/en/latest/usage.html))
- [ ] write user stories as test cases for `renga run` (https://github.com/SwissDataScienceCenter/renga-python/issues/151)

## 4. Push project to a server for sharing 
- [ ] Add an endpoint in the storage to download an object by its checksum (https://github.com/SwissDataScienceCenter/renga-storage/issues/54)
- [ ] Manipulate project access settings in the UI (https://github.com/SwissDataScienceCenter/renga-ui/issues/130)
- [ ] Initialize a project in UI (templates? Gitlab-ci, .renga metadata etc.; https://github.com/SwissDataScienceCenter/renga-ui/issues/129)

## 5. Validate results/workflows
- [ ] schedule a meeting with the Reana team (@jirikuncar)

## 6. UI Improvements, focused on Apr 20 demo
https://github.com/SwissDataScienceCenter/renga-ui/issues/132

## 7. Provide a runnable notebook for exploring new ideas
- [ ] finalize repo cloning (correct branch)
- [ ] enable checking in/pushing changes

## 9. Visualize lineage
- [ ] define lineage views -- where is lineage going to be displayed?
- [ ] provide lineage collected offline to UI for visualization
- [ ] interpret the lineage information in the repo and generate events
- [ ] consume lineage events and produce a view
